
url: "http://localhost"
port: 3000

source:      .
destination: ./_site

title: blog.mklog.fr
description: "@mklabs blog"

lang: 'fr'
permalink: 'articles/:title/'

# exclude - a list of fileglob patterns from the conversion
exclude:
  - 'node_modules/**/*'
  - 'articles/**/*.js'
  - 'oldies/**/*'

# layout - if set, will use this layout as default one when no config is
# found in the front yaml/json config.
layout: 'post'

pages: &pages
  files:
    - '*.html'
    - '**/*.md'
    - '**/*.markdown'
    - 'examples/**/*.js'

watch:
  <<: *pages
