#
### configure nabe
#
#
#### Add your settings here
#
# `set [setting:] [value]`
#
#
#     author:     John Doe                                 # blog author
#     title:      a blog about ...                         # site title
#     date:       yyyy-mm-dd                               # date format for articles
#     disqus:     ''                                       # disqus id, or ''
#     ext:        markdown                                 # file extension for articles
#     feedstart:  Sat Jul 09 2011 18:45:29 GMT+0200 (CEST) # says when feed.xml begins to aggregate stuff
#     summary:                                             # length of article summary and delimiter
#       delim: \n##
#
#
author:       mklabs
title:        blog.mklog.fr
format:       f
culture:      fr
theme:        default
disqus:       ''
ext:          markdown
feedstart:    'Sat Jul 09 2011 19:24:33 GMT+0200 (CEST)'
disqus:       'blogmklog'
summary:
  delim: '<!--more-->|##'
github:
  user: mklabs
  ext: markdown


